version: 0.2

phases:
  pre_build:
     commands:
      - aws --version
      - $(aws ecr get-login --region $AWS_DEFAULT_REGION --no-include-email)
      - REPOSITORY_URI=409244621220.dkr.ecr.ap-southeast-1.amazonaws.com/mvcmovie
      - IMAGE_TAG=$(echo $CODEBUILD_RESOLVED_SOURCE_VERSION | cut -c 1-7)
      - cd MVCApp
      - dotnet restore
  build:
    commands:
      - dotnet build
      - docker build -t $REPOSITORY_URI:latest .
      - docker tag $REPOSITORY_URI:latest $REPOSITORY_URI:$IMAGE_TAG
artifacts:
  files: imagedefinitions.json
