version: 0.2

phases:
  pre_build:
     commands:
      - cd MVCApp
      - dotnet restore
  build:
    commands:      
      - dotnet build
artifacts:
  files:
    - MVCApp/bin/Debug/netcoreapp2.0/*
